version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.12
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-54-83-9-36.compute-1.amazonaws.com
            port: '5432'
            database: d3pul4n9prqiqd
            ssl: true
            user: hzfojnnxkseqmn
            password: 81857883e0aa8a58b113eef8a59f6da39ce7a05193c51494d8a74e109746b1c2
            migrations: true